title: Guillermo Paez # your name (or website title) here
logo: "/images/Foto_CV.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist / Data Analist, Unquillo, Córdoba, Argentina - <a href="/pdf/CV-Guillermo-Paez-2024-11.pdf" target="_blank">CV </a>
  <br><br>
  Mi objetivo es generar valor en las organizaciones a través del diseño e implementación de soluciones de Analítica, DS y ML e IAG, que apoyen la toma de decisiones informadas.
  
theme: jekyll-theme-minimal
