title: Guillermo Paez # your name (or website title) here
logo: "/images/Foto_CV.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Unquillo, Córdoba, Argentina
  <br><br>
  Mi objetivo es desarrollarme como profesional en el ámbito de DS y ML, aportando valor en la toma de decisiones de las organizaciones.
  
theme: jekyll-theme-minimal
